"""
Run BBMap tool on a set of fna files.

This tool serves a distinct purpose separate from collection tools; instead, it is suited for CDM work.
Therefore, the parser program is not compatible with data generated by this tool.

"""
import time
from pathlib import Path

from src.loaders.common.loader_common_names import TOOL_METADATA
from src.loaders.compute_tools.tool_common import ToolRunner, run_command, create_tool_metadata


def _run_bbmap_single(
        tool_safe_data_id: str,
        data_id: str,
        source_file: Path,
        output_dir: Path,
        threads_per_tool_run: int,
        debug: bool) -> None:
    start = time.time()
    print(f'Start executing BBMap for {data_id}')

    metadata_file = output_dir / TOOL_METADATA
    if metadata_file.exists():
        print(f"Skipping {source_file} as it has already been processed.")
        return

    command = [
        'stats.sh',
        'in=' + str(source_file),
        'out=' + str(output_dir / 'result.json'),
        'format=8',  # output in JSON format
        'overwrite=true'
    ]

    run_command(command, output_dir if debug else None)

    end_time = time.time()
    run_time = end_time - start
    print(
        f'Used {round(run_time / 60, 2)} minutes to execute BBMap for {data_id}')

    # Save run info to a metadata file in the output directory for parsing later
    additional_metadata = {
        'source_file': str(source_file),
        'data_id': data_id,
    }
    create_tool_metadata(
        output_dir,
        tool_name="bbmap",
        version="39.06",
        command=command,
        run_time=round(run_time, 2),
        batch_size=1,
        additional_metadata=additional_metadata)


def main():
    runner = ToolRunner("bbmap")
    runner.parallel_single_execution(_run_bbmap_single)


if __name__ == "__main__":
    main()
