FROM continuumio/miniconda3:latest

ENV CHECKM2_VER 1.0.0
ENV CONDA_ENV checkm2-$CHECKM2_VER

RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge

# install CheckM2
RUN git clone --recursive https://github.com/chklovski/checkm2.git
RUN conda env create -n $CONDA_ENV -f checkm2/checkm2.yml

ENV PYTHON_VER 3.8
RUN activate $CONDA_ENV \
    && conda install python=$PYTHON_VER\
    && pip install CheckM2 numpy==1.21

# RUN checkm2 database --download 

RUN mkdir -p /checkm2_root_dir
RUN mkdir -p /checkm2_source_data_dir

RUN mkdir -p /CheckM2_database
ENV CHECKM2DB /CheckM2_database

RUN echo "source activate $CONDA_ENV" >> ~/.bashrc

RUN git clone https://github.com/kbase/collections.git /app/collections

WORKDIR /app

ENV PYTHONPATH /app/collections

ENTRYPOINT ["conda", "run", "-n", "checkm2-1.0.0", "python", "collections/src/loaders/genome_collection/compute_genome_attribs.py"]