FROM continuumio/miniconda3:latest

ENV GTDB_VER 2.1.1
ENV CONDA_ENV gtdbtk-$GTDB_VER
ENV PYTHON_VER 3.8

RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge

RUN conda create -n $CONDA_ENV python=$PYTHON_VER
RUN conda install -n $CONDA_ENV -c conda-forge -c bioconda pandas gtdbtk=$GTDB_VER
RUN conda install -n $CONDA_ENV numpy=1.23.1

RUN echo "source activate $CONDA_ENV" >> ~/.bashrc

RUN mkdir -p /gtdbtk_reference_data

RUN git clone https://github.com/kbase/collections.git /app/collections

WORKDIR /app

ENV GTDBTK_DATA_PATH /gtdbtk_reference_data
ENV PYTHONPATH /app/collections

ENTRYPOINT ["conda", "run", "-n", "gtdbtk-2.1.1", "python", "collections/src/loaders/genome_collection/compute_genome_attribs.py"]