"""
Run eggNOG tool on a set of faa files.

This tool serves a distinct purpose separate from collection tools; instead, it is suited for CDM work.
Therefore, the parser program is not compatible with data generated by this tool.

"""
import time
from pathlib import Path

from src.loaders.common.loader_common_names import TOOL_METADATA
from src.loaders.compute_tools.tool_common import ToolRunner, run_command, create_tool_metadata

INPUT_TYPE = 'proteins'


def _run_eggnog_single(
        tool_safe_data_id: str,
        data_id: str,
        source_file: Path,
        output_dir: Path,
        threads_per_tool_run: int,
        debug: bool) -> None:
    start = time.time()
    print(f'Start executing EggNog for {data_id}')

    metadata_file = output_dir / TOOL_METADATA
    if metadata_file.exists():
        print(f"Skipping {source_file} as it has already been processed.")
        return

    # RUN eggNOG for a single genome
    command = ['emapper.py',
               '-i', source_file,  # Input file.
               '-o', output_dir / source_file.name,  # Output prefix.
               # Save result file to collectiondata directory. Expecting 'emapper.annotations', 'emapper.hits' and  'emapper.seed_orthologs' files.
               '--itype', f'{INPUT_TYPE}',
               '--cpu', f'{threads_per_tool_run}',
               '--excel',
               '--sensmode', 'fast',
               '--dmnd_iterate', 'no',
               '--override'  # Overwrites output files if they exist from previous runs.
               ]

    run_command(command, output_dir if debug else None)

    end_time = time.time()
    run_time = end_time - start
    print(
        f'Used {round(run_time / 60, 2)} minutes to execute EggNog for {data_id}')

    # Save run info to a metadata file in the output directory for parsing later
    additional_metadata = {
        'source_file': str(source_file),
        'data_id': data_id,
        "reference_db": {
            "version": "5.0.2",
        },
    }
    create_tool_metadata(
        output_dir,
        tool_name="eggnog",
        version="2.1.12",
        command=command,
        run_time=round(run_time, 2),
        batch_size=1,
        additional_metadata=additional_metadata)


def main():
    runner = ToolRunner("eggnog")
    runner.parallel_single_execution(_run_eggnog_single, unzip=True)


if __name__ == "__main__":
    main()
