name: Build & Push Tool Image to GHCR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'src/loaders/compute_tools/**/Dockerfile'
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - 'src/loaders/compute_tools/**/Dockerfile'

jobs:
  build-push-tool-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '${{ secrets.GHCR_USERNAME }}'
          password: '${{ secrets.GHCR_TOKEN }}'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Find changed Dockerfiles
        id: find-changed-tools
        run: |
          changed_files=${{ steps.changed-files.outputs.all_changed_files }}
          echo "Changed files: $changed_files"

          IFS=$'\n'
          tools=()
          for file in $changed_files; do
            if [[ "$file" == *"/Dockerfile" ]]; then
              tool=$(basename "$(dirname "$file")")
              tools+=("$tool")
            fi
          done
          echo "changed_tools=${tools[*]}" >> $GITHUB_ENV

      - name: Build and push tool images
        id: build-and-push
        run: |
          tools=(${{ env.changed_tools }})

          for tool in "${tools[@]}"; do
            dockerfile="./src/loaders/compute_tools/$tool/Dockerfile"
            tag="ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:$tool"

            echo "Building and pushing $tool image..."
            echo "tagging image with $tag"

            docker buildx build --file "$dockerfile" --tag "$tag" \
              --build-arg "BUILD_DATE=${{ steps.date.outputs.date }}" \
              --build-arg "VCS_REF=${{ github.sha }}" \
              --build-arg "BRANCH=${{ github.ref }}" \
              --build-arg "TAG=${{ github.ref }}" \
              --push .
          
          done